# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

foo <- function(test) {
    .Call('_RcppHDFql_foo', PACKAGE = 'RcppHDFql', test)
}

